<?php 
session_start();
unset($_SESSION['userId']);	
unset($_SESSION['userName']);	
unset($_SESSION['hospitalId']);	
unset($_SESSION['hospitalName']);	
session_destroy();
header('location:index.php');
?>